repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^(src|scripts)/
      - id: end-of-file-fixer
        files: ^(src|scripts)/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        files: ^(src|scripts)/
      # Run the formatter
      - id: ruff-format
        files: ^(src|scripts)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^(src|scripts)/
        additional_dependencies: [types-requests]